theme = "tale-hugo"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Data Science Diarist"
[params]
highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"

#  syntaxHighlighter = "highlight.js"


  customCSS = ["css/table.css"]
