theme = "tale-hugo"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Data Science Diarist"
[params]
  syntaxHighlighter = "highlight.js"
  highlightjsLang = ["r", "yaml", "tex", "python"]


  customJS = ['https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js']
  customCSS = ["css/table.css"]
