theme = "tale-hugo"
baseURL = "https://datadiarist.github.io/"
languageCode = "en-us"
title = "Data Science Diarist"
[params]
highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
rssLimit = 10

  customCSS = ["css/table.css"]
